export { createCatalog } from "./core/createCatalog";
export type { Catalog, CatalogRecord } from "./core/types";
export { getCatalog, listCatalogs } from "./core/getCatalog";
export type { CatalogName } from "./core/getCatalog";

// mcc has custom bilingual API
export { mcc } from "./catalogs/mcc";
export type { MccRecord, MccLang } from "./catalogs/mcc";
export { actividadEconomica } from "./catalogs/actividad_economica";
export type { ActividadEconomicaRecord } from "./catalogs/actividad_economica";
export { actividadesVulnerables } from "./catalogs/actividades_vulnerables";
export type { ActividadesVulnerablesRecord } from "./catalogs/actividades_vulnerables";
export { ageorincorporationdateSoda } from "./catalogs/ageorincorporationdate_soda";
export type { AgeorincorporationdateSodaRecord } from "./catalogs/ageorincorporationdate_soda";
export { catalogoPrioridad } from "./catalogs/catalogo_prioridad";
export type { CatalogoPrioridadRecord } from "./catalogs/catalogo_prioridad";
export { ccPais } from "./catalogs/cc_pais";
export type { CcPaisRecord } from "./catalogs/cc_pais";
export { cfdiuses } from "./catalogs/cfdiuses";
export type { CfdiusesRecord } from "./catalogs/cfdiuses";
export { cityMexMulaware } from "./catalogs/city_mex_mulaware";
export type { CityMexMulawareRecord } from "./catalogs/city_mex_mulaware";
export { cityMulaware } from "./catalogs/city_mulaware";
export type { CityMulawareRecord } from "./catalogs/city_mulaware";
export { clasificacionActividadEconomica } from "./catalogs/clasificacion_actividad_economica";
export type { ClasificacionActividadEconomicaRecord } from "./catalogs/clasificacion_actividad_economica";
export { claveActividad } from "./catalogs/clave_actividad";
export type { ClaveActividadRecord } from "./catalogs/clave_actividad";
export { claveMoneda } from "./catalogs/clave_moneda";
export type { ClaveMonedaRecord } from "./catalogs/clave_moneda";
export { colonia } from "./catalogs/colonia";
export type { ColoniaRecord } from "./catalogs/colonia";
export { countriesSoda } from "./catalogs/countries_soda";
export type { CountriesSodaRecord } from "./catalogs/countries_soda";
export { countryMulaware } from "./catalogs/country_mulaware";
export type { CountryMulawareRecord } from "./catalogs/country_mulaware";
export { credittermSoda } from "./catalogs/creditterm_soda";
export type { CredittermSodaRecord } from "./catalogs/creditterm_soda";
export { currency } from "./catalogs/currency";
export type { CurrencyRecord } from "./catalogs/currency";
export { currencySoda } from "./catalogs/currency_soda";
export type { CurrencySodaRecord } from "./catalogs/currency_soda";
export { customersenioritySoda } from "./catalogs/customerseniority_soda";
export type { CustomersenioritySodaRecord } from "./catalogs/customerseniority_soda";
export { destinoRecursos } from "./catalogs/destino_recursos";
export type { DestinoRecursosRecord } from "./catalogs/destino_recursos";
export { economicactivitySoda } from "./catalogs/economicactivity_soda";
export type { EconomicactivitySodaRecord } from "./catalogs/economicactivity_soda";
export { enpagosActividadEconomica } from "./catalogs/enpagos_actividad_economica";
export type { EnpagosActividadEconomicaRecord } from "./catalogs/enpagos_actividad_economica";
export { enpagosMunicupio } from "./catalogs/enpagos_municupio";
export type { EnpagosMunicupioRecord } from "./catalogs/enpagos_municupio";
export { enpagosPais } from "./catalogs/enpagos_pais";
export type { EnpagosPaisRecord } from "./catalogs/enpagos_pais";
export { entidadFederativa } from "./catalogs/entidad_federativa";
export type { EntidadFederativaRecord } from "./catalogs/entidad_federativa";
export { girosPagaqui } from "./catalogs/giros_pagaqui";
export type { GirosPagaquiRecord } from "./catalogs/giros_pagaqui";
export { guaranteesSoda } from "./catalogs/guarantees_soda";
export type { GuaranteesSodaRecord } from "./catalogs/guarantees_soda";
export { guaratortypesSoda } from "./catalogs/guaratortypes_soda";
export type { GuaratortypesSodaRecord } from "./catalogs/guaratortypes_soda";
export { instrumentoMonetario } from "./catalogs/instrumento_monetario";
export type { InstrumentoMonetarioRecord } from "./catalogs/instrumento_monetario";
export { localidadMulaware } from "./catalogs/localidad_mulaware";
export type { LocalidadMulawareRecord } from "./catalogs/localidad_mulaware";
export { municipioMulaware } from "./catalogs/municipio_mulaware";
export type { MunicipioMulawareRecord } from "./catalogs/municipio_mulaware";
export { municipios } from "./catalogs/municipios";
export type { MunicipiosRecord } from "./catalogs/municipios";
export { nacionalidad } from "./catalogs/nacionalidad";
export type { NacionalidadRecord } from "./catalogs/nacionalidad";
export { nationalitySoda } from "./catalogs/nationality_soda";
export type { NationalitySodaRecord } from "./catalogs/nationality_soda";
export { numeroTrabajadores } from "./catalogs/numero_trabajadores";
export type { NumeroTrabajadoresRecord } from "./catalogs/numero_trabajadores";
export { ocupationMulaware } from "./catalogs/ocupation_mulaware";
export type { OcupationMulawareRecord } from "./catalogs/ocupation_mulaware";
export { origenRecurso } from "./catalogs/origen_recurso";
export type { OrigenRecursoRecord } from "./catalogs/origen_recurso";
export { pais } from "./catalogs/pais";
export type { PaisRecord } from "./catalogs/pais";
export { paymentForms } from "./catalogs/paymentForms";
export type { PaymentFormsRecord } from "./catalogs/paymentForms";
export { paymentMethods } from "./catalogs/paymentMethods";
export type { PaymentMethodsRecord } from "./catalogs/paymentMethods";
export { persontypeSoda } from "./catalogs/persontype_soda";
export type { PersontypeSodaRecord } from "./catalogs/persontype_soda";
export { pisaActividadEconomica } from "./catalogs/pisa_actividad_economica";
export type { PisaActividadEconomicaRecord } from "./catalogs/pisa_actividad_economica";
export { pisaOcupaciones } from "./catalogs/pisa_ocupaciones";
export type { PisaOcupacionesRecord } from "./catalogs/pisa_ocupaciones";
export { pisaProfesion } from "./catalogs/pisa_profesion";
export type { PisaProfesionRecord } from "./catalogs/pisa_profesion";
export { pisaPuesto } from "./catalogs/pisa_puesto";
export type { PisaPuestoRecord } from "./catalogs/pisa_puesto";
export { prioridad } from "./catalogs/prioridad";
export type { PrioridadRecord } from "./catalogs/prioridad";
export { productsSoda } from "./catalogs/products_soda";
export type { ProductsSodaRecord } from "./catalogs/products_soda";
export { regimenfiscal } from "./catalogs/regimenfiscal";
export type { RegimenfiscalRecord } from "./catalogs/regimenfiscal";
export { relationTypes } from "./catalogs/relationTypes";
export type { RelationTypesRecord } from "./catalogs/relationTypes";
export { resourcedestinationSoda } from "./catalogs/resourcedestination_soda";
export type { ResourcedestinationSodaRecord } from "./catalogs/resourcedestination_soda";
export { resourceoriginSoda } from "./catalogs/resourceorigin_soda";
export type { ResourceoriginSodaRecord } from "./catalogs/resourceorigin_soda";
export { sectorClasificacion } from "./catalogs/sector_clasificacion";
export type { SectorClasificacionRecord } from "./catalogs/sector_clasificacion";
export { states } from "./catalogs/states";
export type { StatesRecord } from "./catalogs/states";
export { statesSoda } from "./catalogs/states_soda";
export type { StatesSodaRecord } from "./catalogs/states_soda";
export { subclasificacionActividad } from "./catalogs/subclasificacion_actividad";
export type { SubclasificacionActividadRecord } from "./catalogs/subclasificacion_actividad";
export { taxonomy } from "./catalogs/taxonomy";
export type { TaxonomyRecord } from "./catalogs/taxonomy";
export { tipoOperacion } from "./catalogs/tipo_operacion";
export type { TipoOperacionRecord } from "./catalogs/tipo_operacion";
export { tipoSociedad } from "./catalogs/tipo_sociedad";
export type { TipoSociedadRecord } from "./catalogs/tipo_sociedad";
export { transactionalfrecuencySoda } from "./catalogs/transactionalfrecuency_soda";
export type { TransactionalfrecuencySodaRecord } from "./catalogs/transactionalfrecuency_soda";
export { transactionamountsSoda } from "./catalogs/transactionamounts_soda";
export type { TransactionamountsSodaRecord } from "./catalogs/transactionamounts_soda";
export { transactionsorsendingchannelsSoda } from "./catalogs/transactionsorsendingchannels_soda";
export type { TransactionsorsendingchannelsSodaRecord } from "./catalogs/transactionsorsendingchannels_soda";
export { zipcode } from "./catalogs/zipcode";
export type { ZipcodeRecord } from "./catalogs/zipcode";
export { zipcodeMulaware } from "./catalogs/zipcode_mulaware";
export type { ZipcodeMulawareRecord } from "./catalogs/zipcode_mulaware";
export { nacionalidad1 } from "./catalogs/Nacionalidad-1";
export type { Nacionalidad1Record } from "./catalogs/Nacionalidad-1";
